const { test, expect } = require('@playwright/test')
test('practice', async ({ page,browser }) => {
    await page.goto('https://www.saucedemo.com/')
    await page.getByPlaceholder('Username').fill('standard_user')
    await page.getByPlaceholder('Password').fill('secret_sauce')
    await page.locator('#login-button').click()
    await expect(page).toHaveURL(/inventory/)
    const productValue = page.locator('.inventory_item_name')
    const TotalProduct  = await productValue.count()
    console.log(`Total Product Count is ${TotalProduct}`)
    const firstProductName = await productValue.first().textContent()
    console.log(`The First Product Name is ${firstProductName}`)
    const context2 = await browser.newContext()
    const newPage = await context2.newPage()
    await newPage.goto('https://www.saucedemo.com/')
    await newPage.getByPlaceholder('Username').fill('problem_user')
    await newPage.getByPlaceholder('Password').fill('secret_sauce')
    await newPage.locator('#login-button').click()
    await expect(newPage).toHaveURL(/inventory/)
        const productValue1 = newPage.locator('.inventory_item_name')
    const TotalProduct1  = await productValue1.count()
    console.log(`Total Product Count is ${TotalProduct1}`)
    const firstProductName1 = await productValue1.first().textContent()
    console.log(`The First Product Name is ${firstProductName1}`)
    await page.bringToFront()
    await expect(page).toHaveURL(/inventory/)
    await page.reload()
    await expect(page).toHaveURL(/inventory/)
    console.log(`Multiple session validation completed successfully`)
})